### ISSUE TITLE
HTTPS files don't seem to work

### ISSUE THREAD

**Issue by ajplopez** [DNNCommunity/DNN.XML#13]
## Please summarize your question in one sentence
An XML feed using https:// doesn't seem to display anything.

## Give a more extended description
I'm trying to display an XML feed that is hosted on another site. The file is https secure. When I enter it into the settings of the module, the content doesn't display. Only files that are local to the DNN file system or non-https (HTTP) files will display content.

## Steps to reproduce (if needed)
1. Edit Module Configuration
2. Data Source Typ: HTTP
3. Location: ( Enter The Address Of The Link ): Put in a hosted XML file that uses https://
4. The content won't display
5. Edit Module Configuration again
6. Enter a hosted XML file that is not HTTPS (http only)
7. You'll see that the non-secure HTTP file works. HTTPS doesn't work.

## Other comments or remarks
DNN 9.3.1
DNN XML 6.0.5

**Comment by ajplopez** [comment]
Here is the feed I'm trying to get to work: https://gms.prevueaps.com/feeds/diversity_by_domain.xml

**Comment by ajplopez** [comment]
FYI: I worked around the issue by using this: https://github.com/davidjrh/dnn.tls12

That said, it would be nice to know more about this issue and if there's a solution in the module itself.

**Comment by valadas** [comment]
The thing with this workaround is that it intercepts all api requests and forces tls1.2 only on everything. This does not scale well when tls1.3 or god knows what is the new requirement or if other endpoints do not support tls1.2, thus could break elsewhere.
Doing OS upgrades and .Net framewrok updates should resolve this issues without resorting to workarounds like this one. It will default to tls1.2 and still support others (negociation) as required. The problem with older .Net framework and unpatched windows versions is that tls1.2 did not exist back then.

**Comment by SCullman** [comment]
Thank you very much for the excellent study of this problem. The XML module (or better: the XmlDataProvider) [uses](https://github.com/DNNCommunity/DNN.XML/blob/0a226a6967c39af7d27637bd6c590b06fecd3046/Providers/XmlDataProvider/HttpRequest/Provider.cs#L135) a [method of the DNN Core](https://github.com/dnnsoftware/Dnn.Platform/blob/435adfc24e7e5c4fa8733a6b1c70dc4effbfecfd/DNN%20Platform/Library/Common/Globals.cs#L2219) to fetch the data. 
David's fix is smart and correct, it enforces TLS 1.2 for all HTTP Requests. It should be part of DNN itself, and there is already a closed [RFC ](https://github.com/dnnsoftware/Dnn.Platform/issues/2603), fix should be part of DNN9.4.0.

**Comment by valadas** [comment]
The discussion on this RFC is what I am saying. The recommendation is to not lock down on any specific implementation but let the system (OS and .Net framework) handle the negociation. The solution is to do the windows updates, this will bring .Net Framework to 4.7.2 and this will be a Dnn 9.4 requirement too, so anybody will be forced to do the updates to even use Dnn when it comes out, thus solving the problem in a safe way. Loking onto tls1.2 for everything may break other modules and is just shovelling forward and pushing the problem to the next time tls recommendations change.

**Comment by SCullman** [comment]
Anyway, I am closing the issue as nothing has to be changed at the XML module.
