### ISSUE TITLE
Outdated request method

### ISSUE THREAD

**Issue by ech01** [DNNCommunity/DNN.XML#2]
When requesting the feed URL, the XML module uses Globals.GetExternalRequest, which uses an outdated request. The GetExternalRequest method is HttpWebRequest and should be changed to use HttpClient https://msdn.microsoft.com/en-us/library/system.net.http.httpclient(v=vs.118).aspx

When requesting secure content, this can cause a transport error. See this related stackexchange: http://stackoverflow.com/questions/35705131/cant-load-dotnetnuke-xml-module-after-security-update-to-tls-1-2

I've come across the same error in the same scenario. I am requesting a feed from a site using TSL 1.2

In lieu of DNN updating the method, the xml module should remove the dependency on the global function and roll with it's own httpclient request.

**Comment by valadas** [comment]
@ech01 the latest release I just published now targets .net 4.5 which should default to TLS 1.2 when available, please give it a try at https://github.com/DNNCommunity/DNN.XML/releases/tag/06.00.05

I am closing this issue, if you can still reproduce after that, please open a new issue and provide some url where we can test a feed with TLS 1.2
