### ISSUE TITLE
Errors in DNN 9.2.2

### ISSUE THREAD

**Issue by b-creative** [DNNCommunity/DNN.XML#7]
Does anyone have the same issues? DNN 9.2.2, XML module 6.0.4 (I had the errors with 6.0.2, hoped that a newer version would resolve the issues but it didn't).

ModuleId:568
ModuleDefId:137
FriendlyName:Eindbeoordeling
ModuleControlSource:DesktopModules/XML/XmlModule.ascx
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:2c8685bd-a95a-409c-9a63-e0ddb547d176
AssemblyVersion:9.2.2
PortalId:0
UserId:1
TabId:149
RawUrl:/
Referrer:https://xxxxxxxxx.nl/DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=228
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
ExceptionHash:NKrsQQ9svYlQ47RT4hxhRIGHugw=
Message:Could not load type 'DotNetNuke.Services.FileSystem.FileController' from assembly 'DotNetNuke, Version=9.2.2.178, Culture=neutral, PublicKeyToken=null'.
StackTrace:
InnerMessage:Could not load type 'DotNetNuke.Services.FileSystem.FileController' from assembly 'DotNetNuke, Version=9.2.2.178, Culture=neutral, PublicKeyToken=null'.
InnerStackTrace:
at DotNetNuke.Modules.Xml.Components.Utils.CreateXmlReader(String xmlsrc, Int32 portalId, Boolean prohibitDtd) at DotNetNuke.Modules.Xml.Providers.XmlRenderingProvider.XslCompiledTransform.Provider.GetXslTransform(String xslsrc, Int32 portalId) at DotNetNuke.Modules.Xml.Providers.XmlRenderingProvider.XslCompiledTransform.Provider.Render(XmlReader reader, TextWriter output, Page page, ModuleInfo moduleConfiguration) at DotNetNuke.Modules.Xml.Components.XmlBaseController.Render(TextWriter output) at DotNetNuke.Modules.Xml.XmlModule.Page_Load(Object sender, EventArgs e)
Source:

FileName:
FileLineNumber:0
FileColumnNumber:0
Method:

**Comment by sleupold** [comment]
I just ran into the same bug. Seem to be caused by removed API in DNN 9.2.0

**Comment by b-creative** [comment]
Any workarounds possible?

**Comment by sleupold** [comment]
no, this needs to be fixed, to run the module in DNN 9.2.0 or later.

**Comment by valadas** [comment]
@b-creative I just published a new release that replaces all deprecated API usages, it will work on Dnn 8.0.0 and up and I tested it up to the current 9.3.0 nightly build. You can download it here https://github.com/DNNCommunity/DNN.XML/releases/tag/06.00.05

**Comment by sleupold** [comment]
Thank you very much, @valadas !

**Comment by b-creative** [comment]
@valadas thats great man, thanks!

**Comment by valadas** [comment]
You are welcome
